# Apply to all files without commiting: pre-commit run --all-files
# Update this file: pre-commit autoupdate

repos:
- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.26.0
  hooks:
  - id: yamllint
    args: [-c=.github/yamllint.config.yaml]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  # - id: check-executables-have-shebangs
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: fix-byte-order-marker
  - id: mixed-line-ending
  - id: check-merge-conflict
  - id: detect-private-key